name:        'upload-artifact-gdrive'
description: 'Upload build artifacts to Google Drive'
author:      'Ecks1337'

inputs:
  name:
    description: 'Artifact file name'
    required:    false

  replaceId:
    description: 'The Google ID of the file to be replaced with the build artifact'
    required:    false

  parentId:
    description: 'The Google ID of the parent folder to put the artifact in'
    required:    false

  path:
    description: 'A file, directory or wildcard pattern that describes what to upload'
    required:    true

  client_id:
    description: 'Google API client id'
    required:    true

  client_secret:
    description: 'Google API secret'
    required:    true

  token:
    description: 'Google API token with the "auth/drive" scope authorised'
    required:    true

  refresh_token:
    description: 'Google API refresh token'
    required:    true

outputs:
  fileId:
    description: 'The Google ID of the artifact after being uploaded'

runs:
  using: 'node12'
  main:  'dist/index.js'